import keyMirror from 'key-mirror';

export default keyMirror({
    SET_PLATFORM: null,
    SET_VERSION: null,

    SESSION_TOKEN_REQUEST: null,
    SESSION_TOKEN_SUCCESS: null,
    SESSION_TOKEN_FAILURE: null,

    DELETE_TOKEN_REQUEST: null,
    DELETE_TOKEN_SUCCESS: null,

    ON_LOGIN_STATE_CHANGE: null,
    LOGOUT: null,

    ON_AUTH_FORM_FIELD_CHANGE: null,

    DELETE_ORGANISATION_REQUEST: null,
    DELETE_ORGANISATION_SUCCESS: null,

    ORGANISATION_LOGIN_REQUEST: null,
    ORGANISATION_LOGIN_SUCCESS: null,
    ORGANISATION_LOGIN_FAILURE: null,

    SET_ORGANISATION_IN_STATE_SUCCESS: null,
    SET_ORGANISATION_IN_STATE_FAILURE: null,

    SET_PROFILE_IN_STATE_SUCCESS: null,
    SET_PROFILE_IN_STATE_FAILURE: null,

    SET_RATINGS_IN_STATE_SUCCESS: null,
    SET_RATINGS_IN_STATE_FAILURE: null,

    LOGIN_REQUEST: null,
    LOGIN_SUCCESS: null,
    LOGIN_FAILURE: null,

    LOGOUT_REQUEST: null,
    LOGOUT_SUCCESS: null,
    LOGOUT_FAILURE: null,

    ORGANISATION_LOGGED_IN: null,
    ORGANISATION_LOGGED_OUT: null,

    LOGGED_IN: null,
    LOGGED_OUT: null,

    SET_SESSION_TOKEN: null,

    RESET_PASSWORD_REQUEST: null,
    RESET_PASSWORD_SUCCESS: null,
    RESET_PASSWORD_FAILURE: null,

    DELETE_PROFILE_REQUEST: null,
    DELETE_PROFILE_SUCCESS: null,

    GET_LOCAL_PROFILE_REQUEST: null,
    GET_LOCAL_PROFILE_SUCCESS: null,
    GET_LOCAL_PROFILE_BLANK_JSON: null,
    GET_LOCAL_PROFILE_FAILURE: null,

    GET_PROFILE_REQUEST: null,
    GET_PROFILE_SUCCESS: null,
    GET_PROFILE_FAILURE: null,

    SET_PROFILE_FORM_FIRST_TIME: null,
    ON_PROFILE_FORM_FIELD_CHANGE: null,

    LOCAL_PROFILE_UPDATE_REQUEST: null,
    LOCAL_PROFILE_UPDATE_SUCCESS: null,
    LOCAL_PROFILE_UPDATE_FAILURE: null,

    PROFILE_UPDATE_REQUEST: null,
    PROFILE_UPDATE_SUCCESS: null,
    PROFILE_UPDATE_FAILURE: null,

    PROFILE_SYNC_REQUEST: null,
    PROFILE_SYNC_SUCCESS: null,
    PROFILE_SYNC_FAILURE: null,

    LOADING_AVATAR_REQUEST: null,
    LOADING_AVATAR_SUCCESS: null,
    LOADING_AVATAR_FAILURE: null,

    DELETE_RATINGS_REQUEST: null,
    DELETE_RATINGS_SUCCESS: null,

    GET_LOCAL_RATINGS_REQUEST: null,
    GET_LOCAL_RATINGS_SUCCESS: null,
    GET_LOCAL_RATINGS_BLANK_JSON: null,
    GET_LOCAL_RATINGS_FAILURE: null,

    GET_RATINGS_REQUEST: null,
    GET_RATINGS_SUCCESS: null,
    GET_RATINGS_FAILURE: null,

    ON_RATING_FORM_FIELD_CHANGE: null,

    LOCAL_RATING_CREATE_REQUEST: null,
    LOCAL_RATING_CREATE_SUCCESS: null,
    LOCAL_RATING_CREATE_FAILURE: null,

    RATING_CREATE_REQUEST: null,
    RATING_CREATE_SUCCESS: null,
    RATING_CREATE_FAILURE: null,

    RATINGS_SYNC_REQUEST: null,
    RATINGS_SYNC_SUCCESS: null,
    RATINGS_SYNC_FAILURE: null,

    DELETE_LOCAL_TOOLS_LIST_REQUEST: null,
    DELETE_LOCAL_TOOLS_LIST_SUCCESS: null,

    GET_LOCAL_TOOLS_LIST_REQUEST: null,
    GET_LOCAL_TOOLS_LIST_SUCCESS: null,
    GET_LOCAL_TOOLS_LIST_BLANK_JSON: null,
    GET_LOCAL_TOOLS_LIST_FAILURE: null,

    GET_TOOLS_LIST_REQUEST: null,
    GET_TOOLS_LIST_SUCCESS: null,
    GET_TOOLS_LIST_FAILURE: null,

    LOCK_VIEW_PAGER: null,
    UNLOCK_VIEW_PAGER: null,

    DELETE_TOOL_SAVES_REQUEST: null,
    DELETE_TOOL_SAVES_SUCCESS: null,

    GET_LOCAL_TOOL_SAVES_LIST_REQUEST: null,
    GET_LOCAL_TOOL_SAVES_LIST_SUCCESS: null,
    GET_LOCAL_TOOL_SAVES_LIST_BLANK_JSON: null,
    GET_LOCAL_TOOL_SAVES_LIST_FAILURE: null,

    GET_LOCAL_TOOL_SAVE_REQUEST: null,
    GET_LOCAL_TOOL_SAVE_SUCCESS: null,
    GET_LOCAL_TOOL_SAVE_BLANK_JSON: null,
    GET_LOCAL_TOOL_SAVE_FAILURE: null,

    GET_TOOL_SAVES_LIST_REQUEST: null,
    GET_TOOL_SAVES_LIST_SUCCESS: null,
    GET_TOOL_SAVES_LIST_FAILURE: null,

    LOCAL_TOOL_SAVE_CREATE_REQUEST: null,
    LOCAL_TOOL_SAVE_CREATE_SUCCESS: null,
    LOCAL_TOOL_SAVE_CREATE_AND_EXIT_SUCCESS: null,
    LOCAL_TOOL_SAVE_CREATE_FAILURE: null,

    LOCAL_TOOL_SAVE_DELETE_REQUEST: null,
    LOCAL_TOOL_SAVE_DELETE_SUCCESS: null,
    LOCAL_TOOL_SAVE_DELETE_FAILURE: null,

    TOOL_SAVE_CREATE_REQUEST: null,
    TOOL_SAVE_CREATE_SUCCESS: null,
    TOOL_SAVE_CREATE_AND_EXIT_SUCCESS: null,
    TOOL_SAVE_CREATE_FAILURE: null,

    TOOL_SAVES_SYNC_REQUEST: null,
    TOOL_SAVES_SYNC_SUCCESS: null,
    TOOL_SAVES_SYNC_FAILURE: null,

    GET_LOCAL_TOOL_REQUEST: null,
    GET_LOCAL_TOOL_SUCCESS: null,
    GET_LOCAL_TOOL_BLANK_JSON: null,
    GET_LOCAL_TOOL_FAILURE: null,

    ON_TOOL_FIELD_CHANGE: null,
    ON_STATIC_TOOL_FIELD_CHANGE: null,
    
    ON_TABLE_ROW_ADD: null,
    ON_TABLE_ROW_DELETE: null,

    SET_STATE: null,
    GET_STATE: null,
    SET_STORE: null,

    NO_ORGANISATION_ID: null,
    ORGANISATION_LOGIN: null,
    LOGIN: null,
    FORGOT_PASSWORD: null,

    GET_AUTHENTICATED_USERS: null,
    GET_RATING_PAGE_VISITS: null,
    GET_TEAM_HISTORICAL_PAGE_VISITS: null,

    ADDED_AUTHENTICATED_USER: null,
    VISITED_RATING_PAGE: null,
    VISITED_TEAM_HISTORICAL_PAGE: null
});
